name: "BCO Core (preview)"
description: "This is the unstable preview track of the BaseCubeOne core system providing a behaviour based automation approach and many more innovative smart home features."
url: "https://www.basecubeone.org"
version: preview-20260115-230517
panel_icon: mdi:cube-outline
slug: "bco-core"
arch:
  - aarch64
  - amd64
startup: application
ports:
  13781/tcp: 13781
image: openbaseorg/bco
map:
  - type: share
    read_only: False
watchdog: http://[HOST]:[PORT:13781]/graphql
timeout: 60
stage: experimental
environment:
  BCO_OPTIONS: "--host addon_f71ff8bf_bco-middleware --port 13780"
  BCO_USER_HOME: "/share/bco/data"
  BCO_HOME: "/share/bco/data"
  BCO_LOGS: "/tmp/logs"
  MQTT_BROKER: "addon_f71ff8bf_bco-middleware"
