name: "BCO Middleware"
description: "Mosquitto MQTT Broker served as middleware for BCO"
version: "0.1.0"
slug: "bco-middleware"
arch:
  - aarch64
  - amd64
startup: services
ports:
  13780/tcp: 13780
